### PR TITLE
Create team pages in admin dashboard

### LINKED ISSUE #87: Include link to teams on admin navbar
Could just link the existing team page, or create a custom one with more information (current guesses, progress, hints, etc.)

### PR DESCRIPTION
**Pull request by brian-xu**
Should unblock #20, #25.

Resolves #87 as well.

### CODE REVIEW

**Comment by brian-xu** [comment]
After thinking about it I don't think this actually unblocks #20 since that would probably need a user-facing team page.

**Comment by qiaochloe** [comment]
Very nice, might need to take more time to read over this. 

The hint table seems to have an extra time column on my screen.
image

**Comment by qiaochloe** [comment]
Functionality works great. 

I have a few UX comments. It feels like there's a lot of shared information between the teams pages and the hinting pages, and I think it might be less confusing if we keep only show that information in the hints page. (Admins won't need to see every guess a particular team has made for each puzzle. But aggregate previous guesses might be helpful on a "puzzles" page.)

I'm thinking that the rows in the team page can link to a _public-facing_ team page instead. On that page, we can have username and password resets, a list of team members (#20) and their locations (if they are in-person), and their current progress through the hunt. I'll bring this up during the next meeting in case people have some other thoughts.

**Comment by brian-xu** [comment]
This is getting to be a pain in the ass so I'm going to close and reopen, see if that fixes anything

**Comment by brian-xu** [comment]
Sorry for the spam, I kept thinking I was done and making changes.
Should finally be ready to review/merge.

**Comment by alex-j-wang** [comment]
Awesome, thanks! I made a couple edits, if they look good feel free to squash and merge.

Couple notes
- Should we try to have the current selections on the team info page pre-filled? For example, have `in-person` checked by default for team that registered as `in-person`. Otherwise, we should put interaction mode somewhere on the team page.
- This is a pretty minor edge case, but demoted users seem to still have admin powers until they log out. Probably won't come up though, may not even be worth the extra processing cost.

**Comment by brian-xu** [comment]
Pre-filling the interaction mode might make the current optional logic a bit weird. The goal is to allow users to be able to change any one attribute at a time. I think displaying the interaction mode is probably cleaner.

As for the demoting users behavior, I actually noticed that while testing and there is server-side logic to prevent any shenanigans. I don't know that fixing the visual bug warrants any bandwidth. https://github.com/qiaochloe/bph-site/blob/d35aa801e3123396aa5963c9292bad7c8c78c6ed/src/app/(hunt)/teams/actions.tsx#L36-L41

I'll add the interaction mode to the team page and merge this tomorrow.

**Comment by qiaochloe** [comment]
OMG this is so cool 🎉 !!

**Pull request merged**
