### PR TITLE
Puzzle unlock system

### PR DESCRIPTION
**Pull request by qiaochloe**
Implemented linear unlocks and adjacency unlocks. The exact ordering of the puzzle unlocks can be specified by the hunt organizer in `hunt.config.ts`.

I also distinguished between solved and unsolved puzzles on the puzzle page (#72), stopped the nav bar from incorrectly caching on login/logout (#120), and tried to fix a lot of miscellaneous bugs regarding `useContext` (partially #43). Notably, I moved context providers to the root layout and replaced bcrypt with bcryptjs, which is a lot more compatible with Next.js for some reason.

The unlock system is not very efficient with database queries. I did index some columns, but I suspect there can be further improvements from (1) limiting the number of columns queries, (2) not doing database queries in middleware, and (3) storing puzzle completion information redundantly in a separate table from guesses. 

Additionally, unlock events only occur when teams solve a puzzle. This means that we can do linear unlocks, adjacency unlocks, and probably round unlocks, but **not time unlocks**. Time unlocks might require a server function. If we want to do **random unlocks**, we might have to think more about how to do that efficiently.

### CODE REVIEW

**Comment by qiaochloe** [comment]
This unlock system is not very efficient with database queries. I did index some columns, but I suspect there can be further improvements from (1) limiting the number of columns queries and (2) storing puzzle completion information redundantly in a separate table from guesses.

**Review by brian-xu — APPROVED** [review]
Overall, LGTM. I do have some thoughts.

https://github.com/qiaochloe/bph-site/blob/0c37d801a46007d7aa6948b8143a59d2991d0283/src/app/(hunt)/puzzle/actions.tsx#L79-L101

Are these lines necessary? I removed them in a local environment and the unlock system seemed to still work. It looks like these lines are here to prevent duplicate unlocks, but with proper hunt config logic that shouldn't be an issue. Duplicate unlocks do show up multiple times on the puzzle list though.

https://github.com/qiaochloe/bph-site/blob/0c37d801a46007d7aa6948b8143a59d2991d0283/src/hunt.config.ts#L47-L59

Any ideas how we would handle an adjacency list unlock with multiple dependencies? We could just query the team's solved puzzles each time but that seems a bit slow.

**Comment by brian-xu** [comment]
Regarding misc bugs in #43, they seem to be most frequent when logging in or traversing dynamic routes. I found tha the server being unable to respond to any request only happens when I execute `npm install` while the dev environment is running.

**Comment by brian-xu** [comment]
Also, something in this PR is breaking the current behavior for invalid puzzle IDs [(example)](https://bph-site.vercel.app/puzzle/example) but I'm not sure what. I assumed it was changes to DefaultPuzzlePage or the middleware but reverting changes in those files didn't solve the issue.

**Comment by qiaochloe** [comment]
> Duplicate unlocks do show up multiple times on the puzzle list though.

I don't want to have duplicate unlocks because the unlock time might be used in some end-of-hunt stats. 
What I currently have should handle adjacency list unlock with multiple dependencies fine.

**Comment by qiaochloe** [comment]
Can put unique requirement on (puzzleId, teamId) for the unlock table. Then just push everything into the unlock table and don't check for duplicates.

**Comment by brian-xu** [comment]
for some reason that was the most painful merge conflict of my life but it seems like we're good to merge

**Review by alex-j-wang — APPROVED** [review]
Thanks guys!

**Pull request merged**
