### PR TITLE
Implement hint limits

### PR DESCRIPTION
**Pull request by qiaochloe**
Just getting this issue rolling. Teams gain a hint request every three hours since the hunt begins, and teams cannot have more than one outstanding hint. This information is displayed below the hint form on every puzzle page.

### CODE REVIEW

**Review by brian-xu — CHANGES_REQUESTED** [review]
Checking hint limits should be done server-side (or at least with zod), since as it stands you can simply remove the disabled tag with inspect element and submit hints anyways.

**Comment by qiaochloe** [comment]
Great catch, I added server-side validation.

**Comment by brian-xu** [comment]
Awesome! LGTM

**Review by brian-xu — APPROVED** [review]

**Comment by qiaochloe** [comment]
Very nice, might need to take more time to read over this. 

The hint table seems to have an extra time column on my screen.
image

**Pull request merged**
